### ISSUE TITLE
Documentation for Setup and Running

### ISSUE THREAD

**Issue by tedsuo** [lightstep/lightstep-benchmarks#56]
Currently there is none.

**Comment by malafeev** [comment]
Able to run on linux with command:
`sudo GOPATH=/home/smalafeev/projects/go PATH=/usr/local/go/bin:$PATH ./benchmark.sh any golang local test`

**Comment by isaaczinda** [comment]
Closing because LightStep Benchmarks has been completely refactored and this is no longer applicable.
